CREATE TABLE IF NOT EXISTS service_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id          BIGINT NOT NULL,
    vehicle_number      VARCHAR(20),
    request_type        VARCHAR(30) NOT NULL,
    priority            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    description         TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    requested_by        VARCHAR(100) NOT NULL,
    approved_by         VARCHAR(100),
    assigned_technician VARCHAR(100),
    resolution_notes    TEXT,
    downtime_hours      DOUBLE PRECISION,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_service_requests_vehicle_active 
ON service_requests (vehicle_id) 
WHERE status IN ('OPEN', 'PENDING_APPROVAL', 'APPROVED', 'ASSIGNED', 'IN_PROGRESS');
